### ISSUE TITLE
Modbus TypeError

### ISSUE THREAD

**Issue by Putinspudding** [nccgroup/fuzzowski#19]
I'm using modbus fuzzer,when it goes to test case 4033, the fuzzowski crashed.
```
$python -m fuzzowski 10.165.198.43 502 -f modbus
[2021-07-20 23:10:57,673]     Info: Using session file: fuzzowski-results/modbus_10.165.198.43_502_tcp_default_d41d8cd98f00b204e9800998ecf8427e.session
Warning: Output is not a terminal (fd=3).
                                       
       ■      ■       
       ■■■■■■■■       
      ■■■■■■■■■■      
     ■■  ■■■■  ■■     
     ■■  ■■■■  ■■     
    ■■■■      ■■■■    
   ■ ■■■■■■■■■■■■ ■   
   ■  ■■■■■■■■■■  ■   Fuzzowski Network Fuzzer
   ■    ■     ■   ■           🄯  Fuzzers, inc.
       ■■     ■■               by Mario Rivas
Fuzzing paused! Welcome to the Fuzzowski Shell
[1 of 10976] ➜ 10.165.198.43:502 $ goto 4032
[4032 of 10976] ➜ 10.165.198.43:502 $ c
[2021-07-20 23:11:05,444] Test Case: 4032: [WriteSingleRegister].output_value.560 
[2021-07-20 23:11:05,447]     Info: Type: Word. Default value: b'\x00\x00'. Case 4032 of 10976 overall.
[2021-07-20 23:11:05,449]     Info: Opening target connection (10.165.198.43:502)...
[2021-07-20 23:11:05,453]     Info: Connection opened.
[2021-07-20 23:11:05,455]   Test Step: Fuzzing node WriteSingleRegister
[2021-07-20 23:11:05,459]     Transmitting 12 bytes: b'\x01\x00\x02\x00\x06\x00\xff\x06\x00\x00\xff\xff'
[2021-07-20 23:11:05,461]     Info: 12 bytes sent
[2021-07-20 23:11:05,464]     Info: Receiving...
[2021-07-20 23:11:10,472]     Received: 
[2021-07-20 23:11:10,474]     Info: Closing target connection...
[2021-07-20 23:11:10,477]     Info: Connection closed.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 398, in <module>
    main()
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 394, in main
    netfuzzer.run()
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 366, in run
    self.session.start()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 184, in start
    self.prompt.start_prompt()
  File "/home/kali/fuzzowski/fuzzowski/prompt/prompt.py", line 90, in start_prompt
    if not self.handle_break(tokens):
  File "/home/kali/fuzzowski/fuzzowski/prompt/session_prompt.py", line 125, in handle_break
    self.session.run_all()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 217, in run_all
    self.run_next(force=False)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 245, in run_next
    self.next()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 376, in next
    self.test_case = next(self._test_cases)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 397, in test_case_iterator
    yield from self.test_case_path_iterator(path)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 408, in test_case_path_iterator
    yield from self.test_case_request_iterator(mutant_request, path)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 420, in test_case_request_iterator
    for _ in request:
  File "/home/kali/fuzzowski/fuzzowski/mutants/mutant.py", line 52, in __next__
    return next(self._mutation_gen)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 70, in _mutation_generator
    for mutation in self.mutant_generator:
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 72, in _mutation_generator
    yield self.render()
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 98, in render
    self._rendered += item.render(replace_node=replace_node, replace_value=replace_value, original=original)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 98, in render
    self._rendered += item.render(replace_node=replace_node, replace_value=replace_value, original=original)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 94, in render
    self._rendered = self._render(self._calculated_length())
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 124, in _calculated_length
    return self.offset + self._inclusive_length_of_self + self._length_of_target_block
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 11, in safe_recurse
    result = f(self, *args, **kwargs)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 135, in _length_of_target_block
    length = len(self.request.get_mutant(self.block_name))
TypeError: 'float' object cannot be interpreted as an integer
```
And following is the code of test case 4033:
```
#!/usr/bin/env python3

import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

sock.connect(('10.165.198.43', 502))

WriteSingleRegister = (
    #Request - WriteSingleRegister
        #Block - modbus_head
        b'\x01\x00'  #Word - transId
        b'\x02\x00'  #Word - protoId
        b'\x06\x00'  #Word - length
        b'\xff'  #Byte - unit Identifier
                #Block - WriteSingleRegisterRequest
                b'\x06'  #Byte - funcCode
                b'\x00\x00'  #Word - output_address
                b'\x00\x00'  #Word - output_value


)
sock.send(WriteSingleRegister)
sock.recv(65535)

sock.close()
```

**Comment by PraveenKumarSoni** [comment]
Getting this error at test case number 4033.

`$python -m fuzzowski 192.168.100.10 502 -f modbus
[2021-07-20 23:10:57,673]     Info: Using session file: fuzzowski-results/modbus_10.165.198.43_502_tcp_default_d41d8cd98f00b204e9800998ecf8427e.session
Warning: Output is not a terminal (fd=3).
                                       
       ■      ■       
       ■■■■■■■■       
      ■■■■■■■■■■      
     ■■  ■■■■  ■■     
     ■■  ■■■■  ■■     
    ■■■■      ■■■■    
   ■ ■■■■■■■■■■■■ ■   
   ■  ■■■■■■■■■■  ■   Fuzzowski Network Fuzzer
   ■    ■     ■   ■           🄯  Fuzzers, inc.
       ■■     ■■               by Mario Rivas
Fuzzing paused! Welcome to the Fuzzowski Shell
[1 of 10976] ➜ 10.165.198.43:502 $ goto 4032
[4032 of 10976] ➜ 10.165.198.43:502 $ c
[2021-07-20 23:11:05,444] Test Case: 4032: [WriteSingleRegister].output_value.560 
[2021-07-20 23:11:05,447]     Info: Type: Word. Default value: b'\x00\x00'. Case 4032 of 10976 overall.
[2021-07-20 23:11:05,449]     Info: Opening target connection (10.165.198.43:502)...
[2021-07-20 23:11:05,453]     Info: Connection opened.
[2021-07-20 23:11:05,455]   Test Step: Fuzzing node WriteSingleRegister
[2021-07-20 23:11:05,459]     Transmitting 12 bytes: b'\x01\x00\x02\x00\x06\x00\xff\x06\x00\x00\xff\xff'
[2021-07-20 23:11:05,461]     Info: 12 bytes sent
[2021-07-20 23:11:05,464]     Info: Receiving...
[2021-07-20 23:11:10,472]     Received: 
[2021-07-20 23:11:10,474]     Info: Closing target connection...
[2021-07-20 23:11:10,477]     Info: Connection closed.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 398, in <module>
    main()
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 394, in main
    netfuzzer.run()
  File "/home/kali/fuzzowski/fuzzowski/__main__.py", line 366, in run
    self.session.start()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 184, in start
    self.prompt.start_prompt()
  File "/home/kali/fuzzowski/fuzzowski/prompt/prompt.py", line 90, in start_prompt
    if not self.handle_break(tokens):
  File "/home/kali/fuzzowski/fuzzowski/prompt/session_prompt.py", line 125, in handle_break
    self.session.run_all()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 217, in run_all
    self.run_next(force=False)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 245, in run_next
    self.next()
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 376, in next
    self.test_case = next(self._test_cases)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 397, in test_case_iterator
    yield from self.test_case_path_iterator(path)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 408, in test_case_path_iterator
    yield from self.test_case_request_iterator(mutant_request, path)
  File "/home/kali/fuzzowski/fuzzowski/session.py", line 420, in test_case_request_iterator
    for _ in request:
  File "/home/kali/fuzzowski/fuzzowski/mutants/mutant.py", line 52, in __next__
    return next(self._mutation_gen)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 70, in _mutation_generator
    for mutation in self.mutant_generator:
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 72, in _mutation_generator
    yield self.render()
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 98, in render
    self._rendered += item.render(replace_node=replace_node, replace_value=replace_value, original=original)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/block.py", line 98, in render
    self._rendered += item.render(replace_node=replace_node, replace_value=replace_value, original=original)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 94, in render
    self._rendered = self._render(self._calculated_length())
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 124, in _calculated_length
    return self.offset + self._inclusive_length_of_self + self._length_of_target_block
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 11, in safe_recurse
    result = f(self, *args, **kwargs)
  File "/home/kali/fuzzowski/fuzzowski/mutants/blocks/size.py", line 135, in _length_of_target_block
    length = len(self.request.get_mutant(self.block_name))
TypeError: 'float' object cannot be interpreted as an integer`

**Comment by PraveenKumarSoni** [comment]
Any help/suggestion??

**Comment by 1modm** [comment]
Sent an update of the modbus module, should be fixed in https://github.com/nccgroup/fuzzowski/pull/26
