### ISSUE TITLE
UDP TypeError: getsockaddrarg

### ISSUE THREAD

**Issue by 1modm** [nccgroup/fuzzowski#8]
Trying to use UDP I'm getting the next error, it seems that the bind address is not set correctly?

```
$python -m fuzzowski 10.32.234.36 47808 -p udp -b 5000 -f testfuzzer
[2019-08-15 09:23:34,448]     Info: Using session file: fuzzowski-results/testfuzzer_10.32.234.36_47808_udp_default_d41d8cd98f00b204e9800998ecf8427e.session
Warning: Output is not to a terminal (fd=6).

       ■      ■
       ■■■■■■■■
      ■■■■■■■■■■
     ■■  ■■■■  ■■
     ■■  ■■■■  ■■
    ■■■■      ■■■■
   ■ ■■■■■■■■■■■■ ■
   ■  ■■■■■■■■■■  ■   Fuzzowski Network Fuzzer
   ■    ■     ■   ■           🄯  Fuzzers, inc.
       ■■     ■■
Fuzzing paused! Welcome to the Fuzzowski Shell
[1 of 224] ➜ 10.32.234.36:47808 $ continue
Exiting prompt...
[2019-08-15 09:23:37,785] Test Case: 1: test_packet.version.1
[2019-08-15 09:23:37,789]     Info: Type: Byte. Default value: b'\x01'. Case 1 of 224 overall.
[2019-08-15 09:23:37,792]     Info: Opening target connection (10.32.234.36:47808)...
[2019-08-15 09:23:37,795]       Check Failed: Cannot connect to target; Retrying...
[2019-08-15 09:23:37,798]     Info: Opening target connection (10.32.234.36:47808)...
[2019-08-15 09:23:37,802]     Error!!!! Cannot connect to target; target presumed down. Note: This likely indicates a failure caused by the previous test case.

[2019-08-15 09:23:37,805]   Test Step: Failure summary
[2019-08-15 09:23:37,809]     Info: Cannot connect to target; Retrying...
[2019-08-15 09:23:37,813]     Error!!!! Unexpected exception! Traceback (most recent call last):
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1351, in _open_fuzzing_target
                                  target.open()
                                File "/tmp/fuzzowski/fuzzowski/connections/target.py", line 52, in open
                                  self._target_connection.open()
                                File "/tmp/fuzzowski/fuzzowski/connections/socket_connection.py", line 123, in open
                                  self._sock.bind(self.bind)
                              TypeError: getsockaddrarg: AF_INET address must be tuple, not int

                              During handling of the above exception, another exception occurred:

                              Traceback (most recent call last):
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1355, in _open_fuzzing_target
                                  target.open()  # Second try, just in case we have a network error not caused by
                                File "/tmp/fuzzowski/fuzzowski/connections/target.py", line 52, in open
                                  self._target_connection.open()
                                File "/tmp/fuzzowski/fuzzowski/connections/socket_connection.py", line 123, in open
                                  self._sock.bind(self.bind)
                              TypeError: getsockaddrarg: AF_INET address must be tuple, not int

                              During handling of the above exception, another exception occurred:

                              Traceback (most recent call last):
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 457, in _main_fuzz_loop
                                  self._fuzz_current_case(*fuzz_args)
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1201, in _fuzz_current_case
                                  self._open_fuzzing_target()
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1359, in _open_fuzzing_target
                                  self._save_last_case_as_suspect(e)
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1474, in _save_last_case_as_suspect
                                  self._go_to_test_case(total_mutant_index - 1)
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1864, in _go_to_test_case
                                  next(self._iterate_single_case_by_index(test_case_index))
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1074, in _iterate_single_case_by_index
                                  for fuzz_args in self._iterate_protocol():
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1010, in _iterate_protocol
                                  self._reset_fuzz_state()
                                File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1454, in _reset_fuzz_state
                                  if self.fuzz_node:
                                File "/tmp/fuzzowski/fuzzowski/blocks/request.py", line 211, in __len__
                                  length += len(item)
                                File "/tmp/fuzzowski/fuzzowski/blocks/block.py", line 282, in __len__
                                  return sum(len(item) for item in self.stack)
                                File "/tmp/fuzzowski/fuzzowski/blocks/block.py", line 282, in <genexpr>
                                  return sum(len(item) for item in self.stack)
                              TypeError: 'float' object cannot be interpreted as an integer

Traceback (most recent call last):
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1351, in _open_fuzzing_target
    target.open()
  File "/tmp/fuzzowski/fuzzowski/connections/target.py", line 52, in open
    self._target_connection.open()
  File "/tmp/fuzzowski/fuzzowski/connections/socket_connection.py", line 123, in open
    self._sock.bind(self.bind)
TypeError: getsockaddrarg: AF_INET address must be tuple, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1355, in _open_fuzzing_target
    target.open()  # Second try, just in case we have a network error not caused by
  File "/tmp/fuzzowski/fuzzowski/connections/target.py", line 52, in open
    self._target_connection.open()
  File "/tmp/fuzzowski/fuzzowski/connections/socket_connection.py", line 123, in open
    self._sock.bind(self.bind)
TypeError: getsockaddrarg: AF_INET address must be tuple, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/fuzzowski/fuzzowski/__main__.py", line 366, in <module>
    main()
  File "/tmp/fuzzowski/fuzzowski/__main__.py", line 362, in main
    netfuzzer.run()
  File "/tmp/fuzzowski/fuzzowski/__main__.py", line 350, in run
    self.session.fuzz()
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 356, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 457, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1201, in _fuzz_current_case
    self._open_fuzzing_target()
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1359, in _open_fuzzing_target
    self._save_last_case_as_suspect(e)
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1474, in _save_last_case_as_suspect
    self._go_to_test_case(total_mutant_index - 1)
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1864, in _go_to_test_case
    next(self._iterate_single_case_by_index(test_case_index))
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1074, in _iterate_single_case_by_index
    for fuzz_args in self._iterate_protocol():
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1010, in _iterate_protocol
    self._reset_fuzz_state()
  File "/tmp/fuzzowski/fuzzowski/sessions.py", line 1454, in _reset_fuzz_state
    if self.fuzz_node:
  File "/tmp/fuzzowski/fuzzowski/blocks/request.py", line 211, in __len__
    length += len(item)
  File "/tmp/fuzzowski/fuzzowski/blocks/block.py", line 282, in __len__
    return sum(len(item) for item in self.stack)
  File "/tmp/fuzzowski/fuzzowski/blocks/block.py", line 282, in <genexpr>
    return sum(len(item) for item in self.stack)
TypeError: 'float' object cannot be interpreted as an integer
```

The test fuzzer used:

```
from typing import List
from .ifuzzer import IFuzzer
from .. import *
from ..sessions import Session


class testfuzzer(IFuzzer):

    name = 'testfuzzer'

    @staticmethod
    def get_requests() -> List[callable]:
        return [testfuzzer.test_packet]

    @staticmethod
    def define_nodes(*args, **kwargs) -> None:
        s_initialize('test_packet')
        # s_string('hola', name='hola')
        
        # if s_block_start("test1"):
        with s_block("test1"):
            s_byte(0x81, name='test2', fuzzable=False)
            s_byte(0xa, name='test3', fuzzable=False)
            s_word(0x0011, name='test4', fuzzable=False)
        # s_block_end()
        with s_block("test5"):
            s_byte(0x1, name='version', fuzzable=True)
            s_byte(0x4, name='control', fuzzable=True)
        # s_block_end()
    # --------------------------------------------------------------- #

    @staticmethod
    def test_packet(session: Session) -> None:
        session.connect(s_get('test_packet'))
```

**Comment by gry** [comment]
Fixed in last commit 7ecf9141.
Thanks for the patience, you seem to be the first one catching them :1st_place_medal: !!
